# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSGApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='school',
            field=models.CharField(default=b'UESTC', max_length=50),
        ),
    ]
