# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSGApp', '0002_auto_20160626_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user',
        ),
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default=0, max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='passwd',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='school',
            field=models.CharField(max_length=50),
        ),
    ]
