# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSGApp', '0003_auto_20160626_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('phone', models.CharField(default=0, max_length=11)),
                ('school', models.CharField(default=b'UESTC', max_length=50)),
                ('studentNo', models.CharField(default=0, max_length=20)),
                ('gender', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
