# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSGApp', '0004_auto_20160626_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
