# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSGApp', '0006_auto_20160626_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInformation',
            fields=[
                ('bookISBN', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=100)),
                ('bookAuthor', models.CharField(max_length=50)),
                ('bookPublisher', models.CharField(max_length=50)),
                ('bookPublishDate', models.CharField(max_length=20)),
                ('bookPrice', models.CharField(max_length=10)),
                ('doubanLink', models.URLField()),
                ('doubanImage', models.URLField()),
                ('doubanRating', models.FloatField()),
                ('doubanSummary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('category', models.CharField(default=0, max_length=50)),
                ('ISBN', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentNo',
            field=models.CharField(max_length=20),
        ),
    ]
