# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSGApp', '0007_auto_20160626_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPriceList',
            fields=[
                ('bookISBN', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bookSaler', models.CharField(max_length=100)),
                ('bookCurrentPrice', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotionID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('promotionCompany', models.CharField(max_length=100)),
                ('promotionName', models.CharField(max_length=100)),
                ('promotionDeadline', models.CharField(max_length=50, null=True)),
                ('promotionLink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PromotionBookList',
            fields=[
                ('promotionID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('promotionBookISBN', models.CharField(max_length=20)),
                ('promotionBookPrice', models.CharField(max_length=10)),
                ('promotionBookCurrentPrice', models.CharField(max_length=10)),
                ('promotionBookSearchLink', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='bookinformation',
            old_name='bookAuthor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='bookinformation',
            old_name='doubanSummary',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='bookinformation',
            old_name='doubanRating',
            new_name='doubanScore',
        ),
        migrations.RenameField(
            model_name='bookinformation',
            old_name='doubanImage',
            new_name='imageLink',
        ),
        migrations.RemoveField(
            model_name='bookinformation',
            name='bookISBN',
        ),
        migrations.RemoveField(
            model_name='bookinformation',
            name='bookPrice',
        ),
        migrations.RemoveField(
            model_name='bookinformation',
            name='bookPublishDate',
        ),
        migrations.RemoveField(
            model_name='bookinformation',
            name='bookPublisher',
        ),
        migrations.RemoveField(
            model_name='userfavourite',
            name='category',
        ),
        migrations.AddField(
            model_name='bookinformation',
            name='ISBN',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinformation',
            name='originalPrice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinformation',
            name='salesLink',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(default=b'UESTC', max_length=50),
        ),
    ]
