# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSGApp', '0008_auto_20160626_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookInformation',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
