# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSGApp', '0009_auto_20160626_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userName',
        ),
        migrations.AddField(
            model_name='promotionbooklist',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfavourite',
            name='bookName',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotionbooklist',
            name='promotionID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentNo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userfavourite',
            name='ISBN',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
